name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-13]
    
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          default: true

      - uses: Swatinem/rust-cache@v1
        with:
          sharedKey: arpchat
      
      - name: winpcap dev pack
        if: ${{ matrix.os }} == windows-latest
        run: |
          mkdir lib
          cd lib
          curl https://doggo.ninja/DRoba9.lib --output Packet.lib
          cd ..
      
      - uses: actions-rs/cargo@v1
        env:
          LIB: ${{ github.workspace }}/lib
        with:
          command: build
          args: --release
      
      - uses: actions/upload-artifact@v3
        with:
          name: release ${{ matrix.os }}
          path: |
            target/release/qqchat*
            !target/release/qqchat.d
          retention-days: 1
